import smtplib
import logging
from email.message import EmailMessage
from pathlib import Path
from src.charts import generate_aa_rate_chart_base64

logger = logging.getLogger(__name__)

def generate_html_report(metrics: dict, report_date: str, sharepoint_links: dict = None, chart_b64: str = "") -> str:
    """Generate the full HTML email body."""
    # Build metrics table rows
    table_rows = ""
    for segment_code, data in metrics.items():
        rate = data["aa_rate"]
        # Color-code the AA rate cell: green if at/above target, red if below
        rate_color = "#2ca02c" if rate >= 85.0 else "#d62728"
        table_rows += f"""
            <tr>
                <td>{data['segment_name']}</td>
                <td>{segment_code}</td>
                <td>{data['total_claims']:,}</td>
                <td>{data['auto_claims']:,}</td>
                <td>{data['manual_claims']:,}</td>
                <td style="color:{rate_color}; font-weight:bold;">{rate:.2f}%</td>
            </tr>"""

    # Build SharePoint links section
    links_section = ""
    if sharepoint_links:
        links_section = "<h3>📁 Report Files (SharePoint)</h3><ul>"
        for filename, url in sharepoint_links.items():
            links_section += f'<li><a href="{url}">{filename}</a></li>'
        links_section += "</ul><p style='color:#888; font-size:12px;'>Files are stored in the Claims Ops SharePoint library and will be available there going forward. No attachments will be sent to preserve inbox capacity.</p>"

    # Inline chart section
    chart_section = ""
    if chart_b64:
        chart_section = f"""
        <h3>📊 AA Rate by Segment</h3>
        <img src="data:image/png;base64,{chart_b64}"
             alt="AA Rate Chart"
             style="max-width:700px; width:100%; border:1px solid #e0e0e0; border-radius:6px; padding:8px;" />
        """

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333333; margin: 0; padding: 20px; }}
            h2   {{ color: #1f4e79; }}
            h3   {{ color: #2c5f8a; margin-top: 24px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
            th, td {{ border: 1px solid #dddddd; padding: 10px 14px; text-align: left; font-size: 13px; }}
            th {{ background-color: #1f4e79; color: #ffffff; }}
            tr:nth-child(even) {{ background-color: #f7f9fc; }}
            a {{ color: #1f4e79; }}
            .footer {{ margin-top: 30px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h2>Daily Auto-Adjudication Report — {report_date}</h2>
        <p>Please find the daily MTD claims summary for <strong>{report_date}</strong> below.</p>

        <h3>📋 Segment Summary</h3>
        <table>
            <tr>
                <th>Segment Name</th>
                <th>Code</th>
                <th>Total Claims</th>
                <th>Auto Claims</th>
                <th>Manual Claims</th>
                <th>AA Rate (%)</th>
            </tr>
            {table_rows}
        </table>

        {chart_section}

        {links_section}

        <div class="footer">
            This is an automated report generated by the Healthcare Claims Reporting Pipeline.<br>
            For issues, contact the Claims Ops automation team.
        </div>
    </body>
    </html>
    """
    return html

def generate_and_send_email(
    metrics: dict,
    email_config: dict,
    sharepoint_links: dict = None,
    report_date: str = "",
):
    """Sends an email with the HTML report and optional attachments using SMTP_SSL."""
    # Generate inline chart
    chart_b64 = generate_aa_rate_chart_base64(metrics, report_date)
    
    html_content = generate_html_report(metrics, report_date, sharepoint_links, chart_b64)
    
    smtp_server = email_config.get('server', 'smtp.gmail.com')
    smtp_port = int(email_config.get('port', 465))
    smtp_user = email_config.get('username', email_config.get('sender'))
    smtp_password = email_config.get('password', '')
    
    msg = EmailMessage()
    base_subject = email_config.get('subject', 'Daily Healthcare Claims Report')
    msg['Subject'] = f"{base_subject} — {report_date}"
    msg['From'] = smtp_user
    msg['To'] = ", ".join(email_config.get('recipients', []))
    
    msg.set_content("Please enable HTML to view this report.")
    msg.add_alternative(html_content, subtype='html')
    
    # No attachments — files are on SharePoint
    try:
        with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
            if smtp_password:
                server.login(smtp_user, smtp_password)
            server.send_message(msg)
        logger.info(f"  Email sent successfully to: {msg['To']}")
    except Exception as e:
        logger.error(f"  Failed to send email: {e}")
        
    # Also save HTML report locally for verification
    from datetime import datetime
    report_filename = f"logs/report_{datetime.today().strftime('%Y%m%d')}.html"
    Path("logs").mkdir(exist_ok=True)
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(html_content)
    logger.info(f"  HTML report saved locally: {report_filename}")

    # ==============================================================================
    # Original win32com (Outlook) corp context implementation (Windows-only)
    # ==============================================================================
    # import win32com.client as win32
    # try:
    #     outlook = win32.Dispatch('outlook.application')
    #     mail = outlook.CreateItem(0)
    #     mail.To = ";".join(email_config.get('recipients', []))
    #     mail.Subject = email_config.get('subject', '')
    #     mail.HTMLBody = html_content
    #     if attachment_path:
    #         mail.Attachments.Add(str(Path(attachment_path).absolute()))
    #     mail.Send()
    #     print("  Email sent via Outlook.")
    # except Exception as e:
    #     print(f"  Failed to send email via Outlook: {e}")